version: "3.0"

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
      - 9229:9229
    command: npm run start:dev
    restart: always
